/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.ldsa.myfintracker;

public final class R {
  public static final class array {
    public static final int landing_page_labels=0x7f010000;
  }
  public static final class color {
    public static final int amountGreen=0x7f020000;
    public static final int background=0x7f020001;
    public static final int badgeOnline=0x7f020002;
    public static final int badgeOnlineText=0x7f020003;
    public static final int badgeRegex=0x7f020004;
    public static final int badgeRegexText=0x7f020005;
    public static final int cardBlue=0x7f020006;
    public static final int cardBlueDark=0x7f020007;
    public static final int cardWhite=0x7f020008;
    public static final int chipActive=0x7f020009;
    public static final int chipInactive=0x7f02000a;
    public static final int chipTextActive=0x7f02000b;
    public static final int chipTextInactive=0x7f02000c;
    public static final int colorAccent=0x7f02000d;
    public static final int colorPrimary=0x7f02000e;
    public static final int colorPrimaryDark=0x7f02000f;
    public static final int danger=0x7f020010;
    public static final int divider=0x7f020011;
    public static final int textHint=0x7f020012;
    public static final int textPrimary=0x7f020013;
    public static final int textSecondary=0x7f020014;
    public static final int white=0x7f020015;
  }
  public static final class drawable {
    public static final int bg_button_danger=0x7f030000;
    public static final int bg_button_primary=0x7f030001;
    public static final int bg_button_secondary=0x7f030002;
    public static final int bg_card=0x7f030003;
    public static final int bg_card_blue=0x7f030004;
    public static final int bg_chip=0x7f030005;
    public static final int bg_chip_active=0x7f030006;
    public static final int bg_fab=0x7f030007;
    public static final int bg_search=0x7f030008;
    public static final int bg_section=0x7f030009;
    public static final int ic_launcher=0x7f03000a;
    public static final int ripple_list_item=0x7f03000b;
  }
  public static final class id {
    public static final int action_add_expense=0x7f040000;
    public static final int action_refresh=0x7f040001;
    public static final int action_settings=0x7f040002;
    public static final int action_sms_inbox=0x7f040003;
    public static final int btnAddLabel=0x7f040004;
    public static final int btnAddSender=0x7f040005;
    public static final int btnFilterAll=0x7f040006;
    public static final int btnFilterMonth=0x7f040007;
    public static final int btnFilterOffline=0x7f040008;
    public static final int btnFilterOnline=0x7f040009;
    public static final int btnSave=0x7f04000a;
    public static final int btnSaveSender=0x7f04000b;
    public static final int btnSortAmount=0x7f04000c;
    public static final int btnSortDate=0x7f04000d;
    public static final int btnSortMerchant=0x7f04000e;
    public static final int btnTestRegex=0x7f04000f;
    public static final int cbIsRegex=0x7f040010;
    public static final int cbOnline=0x7f040011;
    public static final int etAmount=0x7f040012;
    public static final int etAmountRegex=0x7f040013;
    public static final int etBank=0x7f040014;
    public static final int etCard=0x7f040015;
    public static final int etCardRegex=0x7f040016;
    public static final int etDate=0x7f040017;
    public static final int etDateRegex=0x7f040018;
    public static final int etDisplayName=0x7f040019;
    public static final int etMerchant=0x7f04001a;
    public static final int etMerchantRegex=0x7f04001b;
    public static final int etPattern=0x7f04001c;
    public static final int etReason=0x7f04001d;
    public static final int etSearch=0x7f04001e;
    public static final int etTime=0x7f04001f;
    public static final int fabAdd=0x7f040020;
    public static final int labelsLayout=0x7f040021;
    public static final int layoutEditMode=0x7f040022;
    public static final int layoutViewMode=0x7f040023;
    public static final int listExpenses=0x7f040024;
    public static final int listSenders=0x7f040025;
    public static final int listSms=0x7f040026;
    public static final int spinnerLanding=0x7f040027;
    public static final int tvAmount=0x7f040028;
    public static final int tvBank=0x7f040029;
    public static final int tvBankCard=0x7f04002a;
    public static final int tvBody=0x7f04002b;
    public static final int tvCard=0x7f04002c;
    public static final int tvCount=0x7f04002d;
    public static final int tvDate=0x7f04002e;
    public static final int tvEmpty=0x7f04002f;
    public static final int tvLabels=0x7f040030;
    public static final int tvMerchant=0x7f040031;
    public static final int tvNoSenders=0x7f040032;
    public static final int tvOnline=0x7f040033;
    public static final int tvReason=0x7f040034;
    public static final int tvRegexBadge=0x7f040035;
    public static final int tvSender=0x7f040036;
    public static final int tvSenderName=0x7f040037;
    public static final int tvSenderPattern=0x7f040038;
    public static final int tvSms=0x7f040039;
    public static final int tvSmsBody=0x7f04003a;
    public static final int tvSmsCount=0x7f04003b;
    public static final int tvTestResult=0x7f04003c;
    public static final int tvTime=0x7f04003d;
  }
  public static final class layout {
    public static final int activity_add_expense=0x7f050000;
    public static final int activity_expense_detail=0x7f050001;
    public static final int activity_main=0x7f050002;
    public static final int activity_sender_template=0x7f050003;
    public static final int activity_settings=0x7f050004;
    public static final int activity_sms_inbox=0x7f050005;
    public static final int activity_sms_map=0x7f050006;
    public static final int item_expense=0x7f050007;
    public static final int item_sender=0x7f050008;
    public static final int item_sms=0x7f050009;
  }
  public static final class menu {
    public static final int menu_main=0x7f060000;
    public static final int menu_sms=0x7f060001;
  }
  public static final class string {
    public static final int action_add_expense=0x7f070000;
    public static final int action_delete=0x7f070001;
    public static final int action_edit=0x7f070002;
    public static final int action_refresh=0x7f070003;
    public static final int action_save=0x7f070004;
    public static final int action_settings=0x7f070005;
    public static final int action_sms_inbox=0x7f070006;
    public static final int app_name=0x7f070007;
    public static final int btn_add_label=0x7f070008;
    public static final int btn_add_sender=0x7f070009;
    public static final int btn_save=0x7f07000a;
    public static final int btn_save_sender=0x7f07000b;
    public static final int btn_test_regex=0x7f07000c;
    public static final int confirm_delete_expense=0x7f07000d;
    public static final int confirm_delete_sender=0x7f07000e;
    public static final int empty_expenses=0x7f07000f;
    public static final int empty_senders=0x7f070010;
    public static final int empty_sms=0x7f070011;
    public static final int error_amount_required=0x7f070012;
    public static final int error_invalid_amount=0x7f070013;
    public static final int error_pattern_required=0x7f070014;
    public static final int filter_all=0x7f070015;
    public static final int filter_month=0x7f070016;
    public static final int filter_offline=0x7f070017;
    public static final int filter_online=0x7f070018;
    public static final int hint_amount=0x7f070019;
    public static final int hint_bank=0x7f07001a;
    public static final int hint_card=0x7f07001b;
    public static final int hint_date=0x7f07001c;
    public static final int hint_display_name=0x7f07001d;
    public static final int hint_label=0x7f07001e;
    public static final int hint_merchant=0x7f07001f;
    public static final int hint_reason=0x7f070020;
    public static final int hint_regex_amount=0x7f070021;
    public static final int hint_regex_card=0x7f070022;
    public static final int hint_regex_date=0x7f070023;
    public static final int hint_regex_merchant=0x7f070024;
    public static final int hint_search=0x7f070025;
    public static final int hint_sender_pattern=0x7f070026;
    public static final int hint_time=0x7f070027;
    public static final int label_amount=0x7f070028;
    public static final int label_bank=0x7f070029;
    public static final int label_card=0x7f07002a;
    public static final int label_date=0x7f07002b;
    public static final int label_extraction_templates=0x7f07002c;
    public static final int label_is_regex=0x7f07002d;
    public static final int label_labels=0x7f07002e;
    public static final int label_landing_page=0x7f07002f;
    public static final int label_merchant=0x7f070030;
    public static final int label_online=0x7f070031;
    public static final int label_original_sms=0x7f070032;
    public static final int label_reason=0x7f070033;
    public static final int label_sms_senders=0x7f070034;
    public static final int label_time=0x7f070035;
    public static final int msg_expense_deleted=0x7f070036;
    public static final int msg_expense_saved=0x7f070037;
    public static final int msg_sender_deleted=0x7f070038;
    public static final int msg_sender_saved=0x7f070039;
    public static final int perm_sms_required=0x7f07003a;
    public static final int sort_amount=0x7f07003b;
    public static final int sort_date=0x7f07003c;
    public static final int sort_merchant=0x7f07003d;
    public static final int title_add_expense=0x7f07003e;
    public static final int title_expense_detail=0x7f07003f;
    public static final int title_sender_template=0x7f070040;
    public static final int title_settings=0x7f070041;
    public static final int title_sms_inbox=0x7f070042;
    public static final int title_sms_map=0x7f070043;
  }
}